version: '3.8'

services:
  spark-master:
    container_name: da-spark-master
    build: .
    image: da-spark-image
    entrypoint: ['./entrypoint.sh', 'master']
    env_file:
      - .env.spark
    ports:
      - '9090:8080'
      - '7077:7077'


  spark-history-server:
    container_name: da-spark-history
#    build: .
    image: da-spark-image
    entrypoint: ['./entrypoint.sh', 'history']
    depends_on:
      - spark-master
    env_file:
      - .env.spark
    volumes:
      - spark-logs:/tmp/spark-events
    ports:
      - '18080:18080'

  spark-worker:
#    container_name: da-spark-worker
#    build: .
    image: da-spark-image
    entrypoint: ['./entrypoint.sh', 'worker']
    env_file:
      - .env.spark


volumes:
  spark-logs:
